events {}
http {
    include /etc/nginx/mime.types;

    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;

        # Handle all API requests
        # Forward them to the 'maaxly-app' container (on port 4000)
        location /api {
            proxy_pass http://maaxly-app:4000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }

        # Handle all non-API requests (the React App)
        # Try to find the file, then fall back to index.html
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}